/*
Deployment script for ClearMeasure.Bootcamp

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ClearMeasure.Bootcamp"
:setvar DefaultFilePrefix "ClearMeasure.Bootcamp"
:setvar DefaultDataPath "C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column Date on table [dbo].[EfAuditEntry] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[EfAuditEntry])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column Type on table [dbo].[Employee] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[Employee])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[AuditEntry] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[AuditEntry])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Expense] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Expense])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[FK_ExpenseReport_EmployeeForSubmitter]...';


GO
ALTER TABLE [dbo].[ExpenseReport] DROP CONSTRAINT [FK_ExpenseReport_EmployeeForSubmitter];


GO
PRINT N'Dropping [dbo].[FKExpenseReport_EmployeeForApprover]...';


GO
ALTER TABLE [dbo].[ExpenseReport] DROP CONSTRAINT [FKExpenseReport_EmployeeForApprover];


GO
PRINT N'Dropping [dbo].[AuditEntry]...';


GO
DROP TABLE [dbo].[AuditEntry];


GO
PRINT N'Dropping [dbo].[Expense]...';


GO
DROP TABLE [dbo].[Expense];


GO
PRINT N'Starting rebuilding table [dbo].[EfAuditEntry]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_EfAuditEntry] (
    [Id]              UNIQUEIDENTIFIER NOT NULL,
    [Date]            DATETIME2 (7)    NOT NULL,
    [EmployeeId]      UNIQUEIDENTIFIER NULL,
    [EmployeeName]    NVARCHAR (MAX)   NULL,
    [ExpenseReportId] UNIQUEIDENTIFIER NULL,
    [BeginStatus]     NCHAR (3)        NULL,
    [EndStatus]       NCHAR (3)        NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_EfAuditEntry1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[EfAuditEntry])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_EfAuditEntry] ([Id], [ExpenseReportId], [EmployeeId], [EmployeeName], [Date], [BeginStatus], [EndStatus])
        SELECT   [Id],
                 [ExpenseReportId],
                 [EmployeeId],
                 [EmployeeName],
                 [Date],
                 [BeginStatus],
                 [EndStatus]
        FROM     [dbo].[EfAuditEntry]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[EfAuditEntry];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_EfAuditEntry]', N'EfAuditEntry';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_EfAuditEntry1]', N'PK_EfAuditEntry', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[EfAuditEntry].[IX_EfAuditEntry_EmployeeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EfAuditEntry_EmployeeId]
    ON [dbo].[EfAuditEntry]([EmployeeId] ASC);


GO
PRINT N'Creating [dbo].[EfAuditEntry].[IX_EfAuditEntry_ExpenseReportId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EfAuditEntry_ExpenseReportId]
    ON [dbo].[EfAuditEntry]([ExpenseReportId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[Employee]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Employee] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [EmailAddress]     NVARCHAR (100)   NOT NULL,
    [FirstName]        NVARCHAR (25)    NOT NULL,
    [LastName]         NVARCHAR (25)    NOT NULL,
    [Type]             NVARCHAR (MAX)   NOT NULL,
    [UserName]         NVARCHAR (50)    NOT NULL,
    [AdminAssistantId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Employee1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Employee])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Employee] ([Id], [UserName], [FirstName], [LastName], [EmailAddress], [Type], [AdminAssistantId])
        SELECT   [Id],
                 [UserName],
                 [FirstName],
                 [LastName],
                 [EmailAddress],
                 [Type],
                 [AdminAssistantId]
        FROM     [dbo].[Employee]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Employee];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Employee]', N'Employee';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Employee1]', N'PK_Employee', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[Employee].[IX_Employee_AdminAssistantId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Employee_AdminAssistantId]
    ON [dbo].[Employee]([AdminAssistantId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[ExpenseReport]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ExpenseReport] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [ApproverId]     UNIQUEIDENTIFIER NULL,
    [Created]        DATETIME2 (7)    NULL,
    [Description]    NVARCHAR (4000)  NOT NULL,
    [FirstSubmitted] DATETIME2 (7)    NULL,
    [LastApproved]   DATETIME2 (7)    NULL,
    [LastCancelled]  DATETIME2 (7)    NULL,
    [LastDeclined]   DATETIME2 (7)    NULL,
    [LastSubmitted]  DATETIME2 (7)    NULL,
    [LastWithdrawn]  DATETIME2 (7)    NULL,
    [MilesDriven]    INT              NULL,
    [Number]         NVARCHAR (5)     NOT NULL,
    [SubmitterId]    UNIQUEIDENTIFIER NULL,
    [Title]          NVARCHAR (200)   NOT NULL,
    [Total]          DECIMAL (18, 2)  NULL,
    [Status]         NCHAR (3)        NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ExpenseReport1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ExpenseReport])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_ExpenseReport] ([Id], [Number], [Title], [Description], [Status], [SubmitterId], [ApproverId], [MilesDriven], [Created], [FirstSubmitted], [LastSubmitted], [LastWithdrawn], [LastCancelled], [LastApproved], [LastDeclined], [Total])
        SELECT   [Id],
                 [Number],
                 [Title],
                 [Description],
                 [Status],
                 [SubmitterId],
                 [ApproverId],
                 [MilesDriven],
                 [Created],
                 [FirstSubmitted],
                 [LastSubmitted],
                 [LastWithdrawn],
                 [LastCancelled],
                 [LastApproved],
                 [LastDeclined],
                 [Total]
        FROM     [dbo].[ExpenseReport]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[ExpenseReport];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ExpenseReport]', N'ExpenseReport';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_ExpenseReport1]', N'PK_ExpenseReport', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[ExpenseReport].[IX_ExpenseReport_ApproverId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseReport_ApproverId]
    ON [dbo].[ExpenseReport]([ApproverId] ASC);


GO
PRINT N'Creating [dbo].[ExpenseReport].[IX_ExpenseReport_SubmitterId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseReport_SubmitterId]
    ON [dbo].[ExpenseReport]([SubmitterId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[ExpenseReportFact]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ExpenseReportFact] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [Approver]  NVARCHAR (MAX)   NULL,
    [Number]    NVARCHAR (5)     NULL,
    [Status]    NVARCHAR (MAX)   NULL,
    [Submitter] NVARCHAR (MAX)   NULL,
    [TimeStamp] DATETIME2 (7)    NULL,
    [Total]     DECIMAL (18, 2)  NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ExpenseReportFact1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ExpenseReportFact])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_ExpenseReportFact] ([Id], [Number], [TimeStamp], [Total], [Status], [Submitter], [Approver])
        SELECT   [Id],
                 [Number],
                 [TimeStamp],
                 [Total],
                 [Status],
                 [Submitter],
                 [Approver]
        FROM     [dbo].[ExpenseReportFact]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[ExpenseReportFact];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ExpenseReportFact]', N'ExpenseReportFact';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_ExpenseReportFact1]', N'PK_ExpenseReportFact', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_EfAuditEntry_Employee_EmployeeId]...';


GO
ALTER TABLE [dbo].[EfAuditEntry] WITH NOCHECK
    ADD CONSTRAINT [FK_EfAuditEntry_Employee_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([Id]);


GO
PRINT N'Creating [dbo].[FK_EfAuditEntry_ExpenseReport_ExpenseReportId]...';


GO
ALTER TABLE [dbo].[EfAuditEntry] WITH NOCHECK
    ADD CONSTRAINT [FK_EfAuditEntry_ExpenseReport_ExpenseReportId] FOREIGN KEY ([ExpenseReportId]) REFERENCES [dbo].[ExpenseReport] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Employee_Employee_AdminAssistantId]...';


GO
ALTER TABLE [dbo].[Employee] WITH NOCHECK
    ADD CONSTRAINT [FK_Employee_Employee_AdminAssistantId] FOREIGN KEY ([AdminAssistantId]) REFERENCES [dbo].[Employee] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ExpenseReport_Employee_ApproverId]...';


GO
ALTER TABLE [dbo].[ExpenseReport] WITH NOCHECK
    ADD CONSTRAINT [FK_ExpenseReport_Employee_ApproverId] FOREIGN KEY ([ApproverId]) REFERENCES [dbo].[Employee] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ExpenseReport_Employee_SubmitterId]...';


GO
ALTER TABLE [dbo].[ExpenseReport] WITH NOCHECK
    ADD CONSTRAINT [FK_ExpenseReport_Employee_SubmitterId] FOREIGN KEY ([SubmitterId]) REFERENCES [dbo].[Employee] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[EfAuditEntry] WITH CHECK CHECK CONSTRAINT [FK_EfAuditEntry_Employee_EmployeeId];

ALTER TABLE [dbo].[EfAuditEntry] WITH CHECK CHECK CONSTRAINT [FK_EfAuditEntry_ExpenseReport_ExpenseReportId];

ALTER TABLE [dbo].[Employee] WITH CHECK CHECK CONSTRAINT [FK_Employee_Employee_AdminAssistantId];

ALTER TABLE [dbo].[ExpenseReport] WITH CHECK CHECK CONSTRAINT [FK_ExpenseReport_Employee_ApproverId];

ALTER TABLE [dbo].[ExpenseReport] WITH CHECK CHECK CONSTRAINT [FK_ExpenseReport_Employee_SubmitterId];


GO
PRINT N'Update complete.';


GO
